import type { Metadata } from "next"
import "@/styles/globals.sass"

export const metadata: Metadata = {
	title: "DDC",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	)
}
